# .github/workflows/npm-publish-reusable.yml
name: Reusable npm publish

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '22'
      run-tests:
        required: false
        type: boolean
        default: true
      run-build:
        required: false
        type: boolean
        default: true
      run-card:
        required: false
        type: boolean
        default: false
      publish-command:
        required: false
        type: string
        default: 'npm publish --access public --provenance'  # optional but recommended

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: 'https://registry.npmjs.org/'

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Update npm
        run: npm install -g npm@latest

      - name: Test
        if: ${{ inputs.run-tests }}
        run: pnpm test

      - name: Build
        if: ${{ inputs.run-build }}
        run: pnpm build

      - name: Card
        if: ${{ inputs.run-card }}
        run: pnpm card

      - name: Publish
        run: ${{ inputs.publish-command }}
